// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btdiswqfrpdhlqvjdtvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0ZGlzd3FmcnBkaGxxdmpkdHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzAxNjAsImV4cCI6MjA2NTQwNjE2MH0.Vjpuyj_NZo429nMCooMGD2OmLGqlH7bAXpU0Sg0LrWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);